### ISSUE TITLE
生成带logo的二维码可否新增仿微信的样式?

### ISSUE THREAD

**Issue by lydlovezjr** [kangdp/StarBarcode#4]
1.微信图片是在线图片
2.添加白色边框和灰色边框

**Comment by kangdp** [comment]
[QRCodeCodec](https://github.com/kangdongpu/StarBarcode/blob/master/starbarcodelib/src/main/java/com/kdp/starbarcode/codec/QRCodeCodec.java) 改这个类，在logo外层绘制一层矩形边框就行了
